title: AI Blogs
description: Đây là blogs tự học AI-Computer Vision
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one